### ISSUE TITLE
Connect-Keeper doesn't prompt for password

### ISSUE THREAD

**Issue by rotten77** [Keeper-Security/keeper-sdk-dotnet#20]
Steps:

- run Powershell
- exec Connect-Keeper
- enter valid e-mail

![image](https://user-images.githubusercontent.com/2885380/102182683-f7587a80-3eac-11eb-8b13-8e28a0f70d1d.png)

When valid e-mail is entered there is only ":?" that don't accepts any command

**Comment by rotten77** [comment]
Sometimes there is "Press <Enter> to resume" message:

![image](https://user-images.githubusercontent.com/2885380/102183022-78177680-3ead-11eb-8038-cc9d243c054d.png)

**Comment by sk-keeper** [comment]
It means that PowerShell does not support this login step yet.
It could be either SSO or Http Proxy login.
PowerShell script is updated to provide meaningful output.
Http Proxy login is not supported
In order to login to SSO account
1. Ensure Alternate/Master password is created 
2. `Connect-Keeper -SsoPassword` pass -SsoPassword parameter to Connect-Keeper for SSO accounts

**Comment by sk-keeper** [comment]
no response from the customer
