### ISSUE TITLE
Fields parameter Add-KeeperRecord

### ISSUE THREAD

**Issue by Surowa** [Keeper-Security/keeper-sdk-dotnet#98]
There used to be a -Fields parameter on Add-KeeperRecord, is that no longer applicable? Has the syntax changed to create a new record with custom fields?

$record = Add-KeeperRecord -GeneratePassword:$true -Title $sa_description -Fields $fields | Select-Object -ExpandProperty UID
Method invocation failed because [KeeperSecurity.Vault.VaultExtensions] does not contain a method named
'SetCustomField'.
At C:\Program Files\WindowsPowerShell\Modules\PowerCommander\RecordCommands.ps1:395 char:29
+ ...             [KeeperSecurity.Vault.VaultExtensions]::SetCustomField($r ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

**Comment by sk-keeper** [comment]
Thank you for reporting this issue.
`-Fields` parameter is still there. The PowerShell script has not been updated promptly when Keeper sdk library was refactored.
This issue is fixed in `master` branch
https://github.com/Keeper-Security/keeper-sdk-dotnet/commit/87b7b617d769d14d64af3c20559321415f32c281#diff-f53ae20daf16447129b1374eba1d14bcc45040ddd81994f0379685fed354c183

**Comment by Surowa** [comment]
Thank you!
